apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/amarp08/superset-gitops.git'
    targetRevision: HEAD
    path: k8s-spec # Points to the folder with Chart.yaml
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: superset
  syncPolicy:
    automated:
      selfHeal: true
      prune: true